### ISSUE TITLE
[타임라인] 무한스크롤 시 무한루프에 빠지는 코드

### ISSUE THREAD

**Issue by quodvide** [wwh-techcamp-2018/team7-WoowaSmell#27]
- 메인페이지 타임라인에서 리뷰 개수가 0일 때 document.removeEventListener() 메소드가 동작하지 않는 이유 해결하기

**Comment by nigayo** [comment]
생각해보니, 비동기 작업이 끝나고 html이 화면에 추가가 될때까지 scroll이벤트가 들어오면 튕겨버리는 게 명확할 수도 있겠네요.

**Comment by serverwizard** [comment]
팀회의 결과, 스크롤 내려갈 때 throttling을 적용하여 Ajax 호출을 최소화하기로함
