### ISSUE TITLE
[버그] 회원가입이 안돼요ㅠㅠ

### ISSUE THREAD

**Issue by kimyeon0331** [wwh-techcamp-2018/team7-WoowaSmell#78]
인풋 필드 다 채웠는데 회원가입이 그냥 안돼요... 어디가 문제인지 안알려줘서 왜 회원가입이 안되는지 모르겠어요ㅠㅠ

**Comment by Lahavas** [comment]
<img width="1440" alt="2018-08-24 5 09 58" src="https://user-images.githubusercontent.com/16870788/44573447-a1360980-a7c1-11e8-87d4-34828df3c131.png">
요렇게 뜹니다

**Comment by kwonhyeona** [comment]
css 폴더 이동으로 인한 이슈였습니다. 수정했습니다. 감사합니다.
