### ISSUE TITLE
 html/css이슈 남깁니다.

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team7-WoowaSmell#80]
<img width="1275" alt="2018-08-24 5 10 18" src="https://user-images.githubusercontent.com/19792798/44573084-ac3c6a00-a7c0-11e8-83aa-2365781c12c5.png">

화면이 15인치보다 작으면 위에 목록이 아래로 내려가요!

**Comment by kwonhyeona** [comment]
메뉴 css 수정했습니다. 감사합니다.
