### ISSUE TITLE
html/css 관련 이슈

### ISSUE THREAD

**Issue by mindock** [wwh-techcamp-2018/team7-WoowaSmell#81]
리뷰의 길이가 길어지면 화면이 전체적으로 커져요
<img width="1440" alt="2018-08-24 5 12 19" src="https://user-images.githubusercontent.com/32254667/44573166-e60d7080-a7c0-11e8-8e78-f3c9fd3e89a5.png">

**Comment by crongro** [comment]
언젠간 수정되는건가요? ㅎ

**Comment by kwonhyeona** [comment]
@nigayo 아 수정한 후에 데모 진행했습니다!ㅎㅎ
