### ISSUE TITLE
[버그] 텍스트를 길게 해서 등록하기 버튼을 누르면 로그아웃이 됩니다ㅜ

### ISSUE THREAD

**Issue by Lahavas** [wwh-techcamp-2018/team7-WoowaSmell#82]
<img width="516" alt="2018-08-24 5 13 32" src="https://user-images.githubusercontent.com/16870788/44573555-eb1eef80-a7c1-11e8-9d96-8273b7912a5a.png">
요렇게 되네여ㅠ

**Comment by kwonhyeona** [comment]
xss 공격에 대한 이슈였습니다. 해결했습니다. 감사합니다.
