### ISSUE TITLE
카카오톡 로그인이 되지 않습니다.

### ISSUE THREAD

**Issue by hyukjin-lee** [wwh-techcamp-2018/team7-WoowaSmell#83]
에러가 뜨네요
<img width="450" alt="2018-08-24 5 22 32" src="https://user-images.githubusercontent.com/14870706/44573759-7a2c0780-a7c2-11e8-99fc-c9f893f38c7d.png">

**Comment by quodvide** [comment]
감사합니다 카카오톡앱에 도메인 등록하는 곳에 아이피주소만 등록해서 생긴 이슈입니다. 
도메인 등록하여 처리하겠습니다~
